# Project information
site_name: micropython-appengine
# site_url: https://
site_author: Quan Lin
site_description: >-
    A MicroPython app engine.

# Repository
repo_name: micropython-appengine
repo_url: https://github.com/jacklinquan/micropython-appengine
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 <a href="https://github.com/jacklinquan">Quan Lin</a>.

# Path
docs_dir: md_docs
site_dir: docs

# Configuration
theme:
    name: material
    language: en
    features:
        # - navigation.instant
        # - navigation.sections
        # - navigation.tabs
        # - navigation.expand
        - toc.integrate
    palette:
        scheme: default
        primary: indigo
        accent: purple
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/images/favicon_LQ_48x48.png
    logo: assets/images/logo_LQ_20210326.svg
    # icon:
        # logo: logo

# Plugins
plugins:
    - search
    # - redirects:
        # redirect_maps:
            # 'index.md': 'https://quanlin.readthedocs.io/en/latest/'
            # 'old.md': 'new.md'
            # 'old/file.md': 'new/file.md'
            # 'some_file.md': 'http://external.url.com/foobar'
    - awesome-pages
    - mermaid2:
        version: 9.1.3
    - macros:
        module_name: md_docs/scripts/macros_script
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    show_root_heading: false
                    show_root_toc_entry: false
                    members_order: alphabetical
                    docstring_style: google
                    docstring_section_style: table
                    merge_init_into_class: true
                    separate_signature: false
                    show_source: false
    - print-site

# Customization
extra:
    # version:
        # provider: mike
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/jacklinquan
          name: jacklinquan on GitHub
        - icon: fontawesome/solid/print
          link: /print_page
          name: print site

extra_css:
    - assets/css/my_extra.css
    - assets/css/material.css
    - assets/css/mkdocstrings.css

# Extensions
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - toc:
        permalink: "#"
        toc_depth: 4
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.saneheaders
    - pymdownx.smartsymbols
    - pymdownx.snippets:
        base_path: md_docs
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid
    - pymdownx.tabbed
    - pymdownx.tasklist:
        # custom_checkbox: true
    - pymdownx.tilde

extra_javascript:
    - assets/js/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js

# Page tree
nav:
    - Home: index.md
    - api.md
    - ... | blog/**
